apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaspabook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaspabook
  template:
    metadata:
      labels:
        app: kaspabook
    spec:
      containers:
        - name: kaspabook
          image: kaspabook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

